### ISSUE TITLE
Add support for parameters as empty lists

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#45]
This issue captures the work required to support empty list parameters for our binaries. Specifically, consider the following code:

```rust
use structopt::StructOpt;

#[derive(StructOpt)]
struct Options {
    #[structopt(long, env, use_delimiter = true, default_value = "1")]
    my_values: Vec<String>,
}

fn main() {
    println!("{:#?}", Options::from_args().my_values);
}
```

At first glance, there does not appear to be any way to specify an empty list:
```
$ cargo run -q 
[
    "1",
]
$ MY_VALUES='' cargo run -q
[
    "",
]
$ MY_VALUES='1,2' cargo run -q
[
    "1",
    "2",
]
```

This issue seems to affect our services, in our staging configuration we have:
```yaml
global:
  # ...
  unsupportedTokens: '0x0000000000000000000000000000000000000000' # None, work around not supporting empty list.
  # ...
```

> Original issue https://github.com/gnosis/gp-v2-services/issues/660 by @nlordell
